### PR TITLE
Add rubocop and correct most issues.

### PR DESCRIPTION
**Pull request by bdunne**
Cleaning up some white space inconsistency

### CODE REVIEW

**Comment by bdunne** [comment]
@logicminds Please review

**Comment by logicminds** [comment]
can you stick a rubocop file so we can catch these easier next time.

**Comment by bdunne** [comment]
@logicminds I added a .rubocop.yml and cleaned up a bunch of other complaints.  There are a few things left to do, but they are much larger changes than I intended to implement here, so I marked them as TODO in the yml and can revisit them in followup PRs.

It is much easier to review the changes when they are broken out by commit, so that's what I did here.  Let me know and I can squash them before merge if you don't want that much noise in the git history.

**Comment by bdunne** [comment]
@logicminds Thanks!

**Pull request merged**
