### PR TITLE
Change #find_fix to try a different driver

### PR DESCRIPTION
**Pull request by bdunne**
New PR against development branch + rebased.  Based on https://github.com/logicminds/rubyipmi/pull/27

### CODE REVIEW

**Comment by brandondunne** [comment]
@logicminds Did I understand correctly that you wanted the changes rebased against here?

**Comment by logicminds** [comment]
looks good thanks.

**Comment by brandondunne** [comment]
@logicminds Do you want me to change anything else in this PR?

**Comment by brandondunne** [comment]
@logicminds What are your thoughts on this change?

**Comment by logicminds** [comment]
I guess I am not totally sold on the refactor.  The code really just implements the driver logic and I really want the find_fix feature to offer more than just driver replacements. If you were to pass in the 1.5 driver I but it would work for you, as well as your 2.0 devices too since the find_fix feature would fail over to the 2.0 driver.  Send me the exact error messages and I can incorporate them into the error codes (or you can do this yourself too)

**Pull request closed without merging**
